#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="webdesk"
OMV_SERVICE_XPATH="/config/services/$SERVICE_XPATH_NAME"
OMV_SERVICE_CONF="/tmp/$SERVICE_XPATH_NAME.conf"

#Récupération des configs
ENABLE=`omv_config_get "${OMV_SERVICE_XPATH}/enable"`
CONF_NAME="webdesk.conf"

INSTALL_LOG="/etc/webdesk/webdesk_setup_log"
USERNAME="webdesk"
GROUPNAME="webdesk"

#for php7 compatibility / OMV4
FPM_DIR="/etc/php/7.0/fpm/pool.d"
if [ ! -d $FPM_DIR ]
then
    echo "Install failed: no FPM dir detected" > $INSTALL_LOG
    exit 1
fi
FPM_CUSTOM_CONF="${FPM_DIR}/${CONF_NAME}"

if [ $ENABLE -eq 1 ]
then

  if [ ! -f $FPM_CUSTOM_CONF ]
  then

  echo "==> Creating PHP-FPM Config file" >> $INSTALL_LOG

  echo "[webdesk]
user = $USERNAME
group = $GROUPNAME

listen = /var/run/php-omv-webdesk.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

pm = ondemand
pm.max_children = 25
pm.process_idle_timeout = 10s

chdir = /

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; webdesk php.ini settings ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Paths and Directories
php_value[include_path] = \".:/usr/share/php:/var/www/openmediavault\"

; Pam Authentication Support (see /etc/pam.d)
php_value[pam.servicename] = "$USERNAME";

; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
php_value[upload_max_filesize] = 25M

; Maximum size of POST data that PHP will accept.
; http://php.net/post-max-size
php_value[post_max_size] = 25M

; Do not expose to the world that PHP is installed on the server.
; http://php.net/expose-php
php_value[expose_php] = Off

; Name of the session (used as cookie name).
; http://php.net/session.name
php_value[session.name] = X-OPENMEDIAVAULT-WEBDESK-SESSIONID

; Default timeout for socket based streams (seconds)
; http://php.net/default-socket-timeout
php_value[default_socket_timeout] = 90

; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
php_value[max_execution_time] = 90
" > $FPM_CUSTOM_CONF

  echo "==> Restaring php-fpm" >> $INSTALL_LOG

  service php7.0-fpm restart

  echo "restart" >> $INSTALL_LOG
  fi

else

  if [ -f $FPM_CUSTOM_CONF ]
  then
    rm $FPM_CUSTOM_CONF
    service php7.0-fpm restart
  fi

fi


exit 0
