#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="webdesk"
OMV_SERVICE_XPATH="/config/services/$SERVICE_XPATH_NAME"
OMV_SERVICE_CONF="/tmp/$SERVICE_XPATH_NAME.conf"

#Récupération des configs
PORT=`omv_config_get "${OMV_SERVICE_XPATH}/port"`
ENABLE=`omv_config_get "${OMV_SERVICE_XPATH}/enable"`

CONF_NAME="webdesk.conf"
OMV_NGINX_CUSTOM_CONF="/etc/nginx/conf.d/$CONF_NAME"

PROJECT_PATH="/etc/webdesk"
INSTALL_LOG="/etc/webdesk/webdesk_setup_log"
USERNAME="webdesk"
GROUPNAME="webdesk"

#for php7 compatibility / OMV4
FPM_DIR="/etc/php/7.0/fpm/pool.d"
if [ ! -d $FPM_DIR ]
then
    echo "Install failed: no FPM dir detected" > $INSTALL_LOG
fi
FPM_CUSTOM_CONF="${FPM_DIR}/${CONF_NAME}"

if [ $ENABLE -eq 1 ]
then

  #Installation du projet
  if [ ! -d $PROJECT_PATH ]
  then
    mkdir -p $PROJECT_PATH
    echo "Install from latest version" > $INSTALL_LOG
    cd $PROJECT_PATH
    wget http://dl.weberantoine.fr/download.php?file=dist-omv-web-desk.tar.gz -O webdesk.tar.gz
    tar -zxvf webdesk.tar.gz
    rm webdesk.tar.gz
    echo "==> unzipping project" >> $INSTALL_LOG
  else
    echo "Install started from existing dir (debian package)" > $INSTALL_LOG
  fi

  echo "==> Creating NGINX Config file" >> $INSTALL_LOG

  #création ou update de la conf vost nginx
  echo "
  server {
      listen $PORT;
      root $PROJECT_PATH;
      index index.php;
      location ~ \.php$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+?\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-omv-webdesk.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
      }
      access_log /var/log/nginx/webdesk-access.log;
      error_log  /var/log/nginx/webdesk-error.log;
      large_client_header_buffers 4 8k;
  }
  "  > $OMV_NGINX_CUSTOM_CONF

  if [ $(getent group $GROUPNAME) ]; then
    echo "==> Group '$GROUPNAME' Already Exist" >> $INSTALL_LOG
  else
    echo "==> Creating linux group webdesk" >> $INSTALL_LOG
    groupadd $GROUPNAME
  fi

  if [ `id -u $USERNAME 2>/dev/null || echo -1` -ge 0 ]; then
    echo "==> Account '$USERNAME' Already Exist" >> $INSTALL_LOG
  else
    echo "==> Creating linux user webdesk" >> $INSTALL_LOG

    useradd $USERNAME -g $GROUPNAME

    echo "==> add user to needed groups" >> $INSTALL_LOG

    usermod -a -G users $USERNAME
    usermod -a -G www-data $USERNAME
    usermod -a -G openmediavault-config $USERNAME
    usermod -a -G openmediavault-engined $USERNAME
    usermod -a -G openmediavault-webgui $USERNAME
  fi

  echo "==> Creating PHP-FPM Config file" >> $INSTALL_LOG

  echo "[webdesk]
user = $USERNAME
group = $GROUPNAME

listen = /var/run/php-omv-webdesk.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

pm = ondemand
pm.max_children = 25
pm.process_idle_timeout = 10s

chdir = /

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; webdesk php.ini settings ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Paths and Directories
php_value[include_path] = \".:/usr/share/php:/var/www/openmediavault\"

; Pam Authentication Support (see /etc/pam.d)
php_value[pam.servicename] = "$USERNAME";

; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
php_value[upload_max_filesize] = 25M

; Maximum size of POST data that PHP will accept.
; http://php.net/post-max-size
php_value[post_max_size] = 25M

; Do not expose to the world that PHP is installed on the server.
; http://php.net/expose-php
php_value[expose_php] = Off

; Name of the session (used as cookie name).
; http://php.net/session.name
php_value[session.name] = X-OPENMEDIAVAULT-WEBDESK-SESSIONID

; Default timeout for socket based streams (seconds)
; http://php.net/default-socket-timeout
php_value[default_socket_timeout] = 90

; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
php_value[max_execution_time] = 90
" > $FPM_CUSTOM_CONF

  if [ ! -f /etc/nginx/sites-available/$CONF_NAME ]
  then
    echo "==> Link NGINX Config in sites-available" >> $INSTALL_LOG
    ln -s $OMV_NGINX_CUSTOM_CONF /etc/nginx/sites-available/$CONF_NAME
  fi

  echo "==> Restaring nginx and php-fpm" >> $INSTALL_LOG

  service nginx restart
  service php7.0-fpm restart

  echo "restart" >> $INSTALL_LOG
else
  ##supression du vhost
  if [ -f /etc/nginx/sites-available/$CONF_NAME ]
  then
    rm /etc/nginx/sites-available/$CONF_NAME
  fi

  #supression des conf
  if [ -f $OMV_NGINX_CUSTOM_CONF ]
  then
    rm $OMV_NGINX_CUSTOM_CONF
  fi
  if [ -f $FPM_CUSTOM_CONF ]
  then
    rm $FPM_CUSTOM_CONF
  fi


  ##suppression du projet
  #if [ -d $PROJECT_PATH ]
  #then
  #  rm -rf $PROJECT_PATH
  #fi

  #suppression du user si existant
  if [ `id -u $USERNAME 2>/dev/null || echo -1` -ge 0 ]; then
    deluser $USERNAME
  fi
  if [ $(getent group $GROUPNAME) ]; then
    delgroup $GROUPNAME
  fi

  service nginx restart
  service php7.0-fpm restart

fi


exit 0
