#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="webdesk"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        INSTALL_LOG="/etc/webdesk/webdesk_setup_log"
        USERNAME="webdesk"
        GROUPNAME="webdesk"

        # Add the default configuration
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_key "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "name" "WebDesk for OpenMediaVault"
            omv_config_add_key "${SERVICE_XPATH}" "port" "90"
            omv_config_add_node "${SERVICE_XPATH}" "links"
        fi

        if [ $(getent group $GROUPNAME) ]; then
          echo "==> Group '$GROUPNAME' Already Exist" >> $INSTALL_LOG
        else
          echo "==> Creating linux group webdesk" >> $INSTALL_LOG
          groupadd $GROUPNAME
        fi

        if [ `id -u $USERNAME 2>/dev/null || echo -1` -ge 0 ]; then
          echo "==> Account '$USERNAME' Already Exist" >> $INSTALL_LOG
        else
          echo "==> Creating linux user webdesk" >> $INSTALL_LOG

          useradd $USERNAME -g $GROUPNAME

          echo "==> add user to needed groups" >> $INSTALL_LOG

          usermod -a -G users $USERNAME
          usermod -a -G www-data $USERNAME
          usermod -a -G openmediavault-config $USERNAME
          usermod -a -G openmediavault-engined $USERNAME
          usermod -a -G openmediavault-webgui $USERNAME
        fi


        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
