#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="webdesk"
OMV_SERVICE_XPATH="/config/services/$SERVICE_XPATH_NAME"
OMV_SERVICE_CONF="/tmp/$SERVICE_XPATH_NAME.conf"

#Récupération des configs
PORT=`omv_config_get "${OMV_SERVICE_XPATH}/port"`
ENABLE=`omv_config_get "${OMV_SERVICE_XPATH}/enable"`

CONF_NAME="webdesk.conf"
OMV_NGINX_CUSTOM_CONF="/etc/nginx/conf.d/$CONF_NAME"
PROJECT_PATH="/etc/webdesk"

if [ $ENABLE -eq 1 ]
then

  #Installation du projet
  if [ ! -d $PROJECT_PATH ]
  then
    mkdir -p $PROJECT_PATH
    cd $PROJECT_PATH
    wget http://dl.weberantoine.fr/download.php?file=dist-omv-web-desk.tar.gz -O webdesk.tar.gz
    tar -zxvf webdesk.tar.gz
  fi

  #création ou update de la conf vost nginx
  echo "
  server {
      listen $PORT;
      listen [::]:$PORT;
      set \$root_path "$PROJECT_PATH";
      root \$root_path;
      index index.php;
      set \$socket "unix:/var/run/php-fpm-openmediavault-webgui.sock";
      location ~ \.php$ {
          #include snippets/fastcgi-php.conf;
          fastcgi_pass \$socket;
      }
      access_log /var/log/nginx/webdesk-access.log;
      error_log  /var/log/nginx/webdesk-error.log;
      large_client_header_buffers 4 8k;
  }
  "  > $OMV_NGINX_CUSTOM_CONF

  ln -s $OMV_NGINX_CUSTOM_CONF /etc/nginx/sites-available/$CONF_NAME

  service nginx restart
else
  ##supression du vhost
  rmlink /etc/nginx/sites-available/$CONF_NAME
  rm $OMV_NGINX_CUSTOM_CONF

  ##suppression du projet
  rm -rf $PROJECT_PATH
fi


exit 0
